import type { ReadingSet } from "./types";
import { mcq, tf } from "./helpers";

// Textos originales escritos para la app (no reproducen material protegido de exámenes).
export const READINGS_1: ReadingSet[] = [
  {
    id: "r-tone", title: "Tone Is Not Exotic", discipline: "phonology", genre: "expository", lvl: 62,
    paragraphs: [
      "For speakers of European languages, the idea that the pitch of a syllable can change the meaning of a word often seems strange. In English, raising the voice at the end of a sentence may turn a statement into a question, but it does not turn one word into another. In a tone language, by contrast, pitch works much like a consonant or a vowel: it is part of the word itself. In Mandarin, for example, the syllable *ma* can mean 'mother', 'hemp', 'horse' or 'scold', depending on its pitch contour.",
      "Tone is far from rare. In one widely used typological database, roughly two in five of the languages sampled have tonal contrasts of some kind. Tone languages are concentrated in sub-Saharan Africa, East and Southeast Asia, and parts of the Americas, including many Indigenous languages of Mexico. If anything, it is the European pattern that is geographically unusual, which suggests that our intuitions about what counts as 'normal' in phonology are shaped largely by the languages we happen to know.",
      "How do languages acquire tone in the first place? One well-documented pathway, known as tonogenesis, begins with consonants. Voiced consonants such as /b/ or /d/ tend to lower the pitch of the following vowel slightly, while voiceless consonants tend to raise it. Normally, listeners treat these pitch differences as a side effect of the consonant. If, however, the voicing contrast itself is weakened or lost, the pitch difference may be the only cue left to distinguish words, and speakers may reinterpret it as a property of the vowel. Over generations, a phonetic by-product can thus become a phonological contrast. A version of this scenario has been proposed for Vietnamese and several other languages of mainland Southeast Asia.",
      "Tone systems are not all alike. Some languages contrast only two levels, high and low; others distinguish several levels and contours that rise, fall or do both. Moreover, tones often interact with one another in connected speech. In what linguists call tone sandhi, the tone of one syllable changes depending on the tones around it, so that the citation form of a word may rarely surface in natural conversation. This poses obvious challenges for field linguists, who must decide which pattern is basic and which is derived.",
      "Writing tone is another source of debate. Some orthographies mark every tone with a diacritic; others mark tone only where confusion is likely, and many mark it not at all, relying on context. Advocates of full marking argue that it supports learners and preserves information that may otherwise be lost. Critics respond that heavy diacritics can make texts harder for fluent readers and that native speakers rarely need them. The right choice probably depends less on linguistic theory than on who the readers are and what the written language is used for.",
    ],
    questions: [
      mcq("rt1", "rd:main-idea", 60, "What is the main purpose of the passage?", [
        "To argue that tone languages are harder to learn than other languages",
        "To show that tone is a common, systematic and varied feature of human languages",
        "To explain how Mandarin developed its tones",
        "To recommend a single system for writing tone"], 1,
        "Each paragraph contributes to one idea: tone is widespread (P2), arises systematically (P3), varies (P4) and raises practical questions (P5).",
        ["Difficulty is never discussed.", null, "Mandarin is only an example in P1; tonogenesis is discussed for Vietnamese.", "P5 explicitly avoids recommending one system."], ["out-of-scope", null, "too-specific", "contradicts"]),
      mcq("rt2", "rd:detail", 58, "According to paragraph 2, approximately what proportion of the languages in the database have tone?", ["About 20%", "About 40%", "More than half", "Almost all"], 1, "*Roughly two in five* ≈ 40%.", ["Understates the figure.", null, "Overstates the figure.", "Far too extreme."], [null, null, "too-extreme", "too-extreme"]),
      mcq("rt3", "rd:inference", 64, "What does the author imply in paragraph 2 about European languages?", [
        "They are less complex than tone languages.",
        "They are an unreliable basis for judging what is typical in phonology.",
        "They once had tone but lost it.",
        "They are spoken in more countries than tone languages."], 1,
        "*Our intuitions about what counts as 'normal'… are shaped largely by the languages we happen to know*: European languages are not a neutral reference point.",
        ["Complexity isn't compared.", null, "Never stated.", "Number of countries is never mentioned."], ["out-of-scope", null, "true-not-stated", "out-of-scope"]),
      mcq("rt4", "rd:vocab", 60, "The word **by-product** in paragraph 3 is closest in meaning to…", ["a secondary effect", "a final result", "a deliberate change", "a written symbol"], 0, "A *by-product* is something produced incidentally while something else happens — here, pitch as a side effect of consonants (cf. *side effect* earlier in the paragraph)."),
      mcq("rt5", "rd:organization", 64, "Which sequence best summarises tonogenesis as described in paragraph 3?", [
        "Pitch differences appear → voicing is lost → consonants change",
        "Consonants affect pitch → the voicing contrast weakens → pitch becomes the distinguishing feature",
        "Speakers invent tones → consonants disappear → vowels lengthen",
        "Vowels change pitch → consonants become voiced → tones are written"], 1,
        "The order in the text: consonant voicing affects pitch → voicing contrast is lost → pitch is reinterpreted as contrastive.", [null, null, null, null], ["reversed", null, "out-of-scope", "reversed"]),
      mcq("rt6", "rd:reference", 58, "In paragraph 4, **This** in 'This poses obvious challenges' refers to…", ["the fact that tones change in context, so the citation form may rarely appear", "the number of tone levels", "the work of field linguists", "the citation form of a word"], 0, "*This* summarises the previous sentence: tones change in connected speech, so the basic form may rarely surface."),
      mcq("rt7", "rd:attitude", 66, "What is the author's position on how tone should be written?", [
        "Every tone should be marked.",
        "Tone should never be marked.",
        "The best solution depends on the readers and the uses of the written language.",
        "Linguistic theory should decide the matter."], 2,
        "*The right choice probably depends less on linguistic theory than on who the readers are…* — a hedged, context-dependent position.",
        ["That's the advocates' view, which the author reports but doesn't adopt.", "That's closer to the critics, but the author doesn't adopt it either.", null, "The author says theory matters *less*."], ["word-match", "partial", null, "reversed"]),
      tf("rt8", "rd:detail", 62, "Tone sandhi makes the citation form of words more frequent in conversation.", "F", "The text says the citation form *may rarely surface* in natural conversation — the opposite."),
    ],
    annotations: [
      { p: 1, q: "roughly two in five of the languages sampled have tonal contrasts", type: "evidence", note: "Quantitative evidence, deliberately approximate (*roughly*)." },
      { p: 1, q: "which suggests that our intuitions about what counts as 'normal' in phonology are shaped largely by the languages we happen to know", type: "claim", note: "The paragraph's real claim, hedged with *suggests* and *largely*." },
      { p: 2, q: "A version of this scenario has been proposed", type: "hedge", note: "*Has been proposed* reports a hypothesis without asserting it as fact." },
      { p: 4, q: "Advocates of full marking argue", type: "counter", note: "First position in a debate." },
      { p: 4, q: "Critics respond", type: "counter", note: "Opposing position: the writer presents both sides before concluding." },
      { p: 4, q: "The right choice probably depends less on linguistic theory than on who the readers are", type: "stance", note: "The writer's own position — hedged (*probably*) and comparative." },
    ],
  },
  {
    id: "r-teeth", title: "What Ancient Teeth Remember", discipline: "archaeology", genre: "expository", lvl: 66,
    paragraphs: [
      "Of all the parts of the human body, teeth are among the most durable. Long after soft tissue has decayed and many bones have crumbled, teeth often survive in recognisable form. For archaeologists, this resilience makes them an unusually rich archive, and in recent decades new laboratory techniques have allowed researchers to extract from them information that earlier generations could only have guessed at.",
      "One source of evidence is dental calculus, the hardened plaque that builds up on teeth when they are not cleaned. As it forms, calculus traps tiny particles from the mouth: starch grains from cooked plants, fragments of plant tissue, even microscopic traces of smoke. Because it mineralises during the person's lifetime, it also preserves DNA from the bacteria that lived in the mouth. Analysing these materials can reveal not only what people ate but also something about their health and, in some cases, about activities such as using the teeth as tools.",
      "A second approach relies on the chemistry of tooth enamel. Enamel forms in childhood and, unlike bone, is not remodelled afterwards. The ratios of certain isotopes in enamel, notably of strontium and oxygen, reflect the local geology and water sources of the place where the person lived as a child. By comparing these ratios with those of the area where the individual was buried, researchers can sometimes determine whether that person grew up locally or migrated from elsewhere. Studies of this kind have challenged assumptions that ancient communities were largely sedentary, revealing in several cases that a substantial minority of individuals buried at a site had arrived from other regions.",
      "These methods are powerful, but they are not without problems. Calculus can be contaminated by modern bacteria during excavation or handling, and isotope values from different regions sometimes overlap, so that a 'local' signature may be consistent with several possible places of origin. Moreover, the individuals whose remains survive and are excavated are not necessarily representative of the population as a whole: burial customs, soil conditions and the choices of past excavators all shape the sample.",
      "None of this means that the findings should be dismissed. Rather, it means that dental evidence is most convincing when it is combined with other lines of evidence — archaeological context, written sources where they exist, and ancient DNA from the individuals themselves. Teeth remember a great deal, but, like all witnesses, they need to be cross-examined.",
    ],
    questions: [
      mcq("te1", "rd:main-idea", 62, "Which statement best expresses the main idea?", [
        "Teeth provide valuable but imperfect evidence about past lives, best interpreted alongside other sources.",
        "Dental calculus is the most important evidence in archaeology.",
        "Ancient people migrated more than modern people.",
        "Isotope analysis has replaced traditional archaeology."], 0,
        "The text presents two methods (P2–3), their limitations (P4) and the need to combine evidence (P5).",
        [null, "Overstates calculus; it's one of two methods.", "Never compared with modern people.", "The last paragraph says the opposite: combine methods."], [null, "too-extreme", "out-of-scope", "contradicts"]),
      mcq("te2", "rd:detail", 60, "Why is enamel useful for studying where a person grew up?", [
        "It forms in childhood and does not change afterwards.",
        "It contains bacteria from the mouth.",
        "It is harder than bone.",
        "It absorbs water throughout life."], 0, "*Enamel forms in childhood and, unlike bone, is not remodelled afterwards.*",
        [null, "That's calculus, not enamel.", "Durability is mentioned in P1, but it's not why enamel reveals childhood location.", "Contradicts *not remodelled*."], [null, "word-match", "wrong-focus", "contradicts"]),
      mcq("te3", "rd:inference", 66, "What can be inferred about earlier views of ancient communities?", [
        "They assumed most people stayed in the same place all their lives.",
        "They assumed most people migrated frequently.",
        "They were based on isotope studies.",
        "They ignored teeth entirely."], 0, "New studies *challenged assumptions that ancient communities were largely sedentary* → earlier views assumed little movement.",
        [null, "Opposite.", "Isotope studies are what challenged them.", "Too extreme: not stated."], [null, "reversed", "reversed", "too-extreme"]),
      mcq("te4", "rd:vocab", 62, "The word **sedentary** in paragraph 3 is closest in meaning to…", ["settled in one place", "physically inactive", "agricultural", "isolated"], 0,
        "In the context of migration, *sedentary* = living in one place (not nomadic). The everyday meaning 'physically inactive' doesn't fit here.",
        [null, "Common meaning, but wrong in this context.", "Related but not the meaning.", "Not the meaning."], [null, "possible-not-correct", "too-specific", null]),
      mcq("te5", "rd:purpose", 66, "Why does the author mention burial customs and soil conditions in paragraph 4?", [
        "To explain why surviving remains may not represent the whole population",
        "To describe how teeth are preserved",
        "To show that excavators make mistakes",
        "To argue that isotope values overlap"], 0, "They are examples of factors that *shape the sample*, making it unrepresentative."),
      mcq("te6", "rd:attitude", 68, "The author's attitude to dental evidence is best described as…", ["enthusiastic but critical", "dismissive", "uncritically positive", "neutral and uninterested"], 0, "*Powerful, but… not without problems*; *None of this means… dismissed* — appreciation with caution."),
      mcq("te7", "rd:paraphrase", 70, "Which is the best paraphrase of the final sentence?", [
        "Teeth provide abundant information, but it must be tested against other evidence.",
        "Teeth are unreliable witnesses and should not be used.",
        "Archaeologists should interview living people.",
        "Teeth remember more than bones do."], 0, "The metaphor: witnesses are valuable, but their testimony must be checked (*cross-examined*).",
        [null, "Too negative: the author values the evidence.", "Literal misreading of the metaphor.", "Comparison not made in the sentence."], [null, "too-extreme", "word-match", "out-of-scope"]),
      tf("te8", "rd:detail", 64, "Dental calculus can preserve bacterial DNA.", "T", "*It also preserves DNA from the bacteria that lived in the mouth.*"),
      tf("te9", "rd:detail", 66, "Most individuals buried at the sites studied had migrated from other regions.", "F", "The text says *a substantial minority*, not most."),
      tf("te10", "rd:detail", 68, "Strontium analysis is more expensive than calculus analysis.", "NG", "Cost is never mentioned."),
    ],
    annotations: [
      { p: 0, q: "new laboratory techniques have allowed researchers to extract from them information", type: "claim", note: "Framing claim: what's new and why teeth matter." },
      { p: 2, q: "researchers can sometimes determine", type: "hedge", note: "*Sometimes*: limits the scope of the claim." },
      { p: 2, q: "Studies of this kind have challenged assumptions that ancient communities were largely sedentary", type: "evidence", note: "Evidence that overturns a previous view." },
      { p: 3, q: "These methods are powerful, but they are not without problems.", type: "limit", note: "Explicit limitation move." },
      { p: 3, q: "are not necessarily representative of the population as a whole", type: "limit", note: "Sampling bias — a classic limitation." },
      { p: 4, q: "dental evidence is most convincing when it is combined with other lines of evidence", type: "stance", note: "Writer's conclusion: triangulation." },
    ],
  },
  {
    id: "r-transit", title: "Planets in the Shadows", discipline: "astronomy", genre: "expository", lvl: 70,
    paragraphs: [
      "Until the 1990s, no planet had been confirmed orbiting a Sun-like star other than our own. Today, the number of known exoplanets runs into the thousands. Much of this transformation is due to a deceptively simple idea: when a planet passes in front of its star, as seen from Earth, it blocks a small fraction of the star's light. By monitoring the brightness of many stars over long periods, astronomers can detect these regular, tiny dips, an approach known as the transit method.",
      "The amount by which the star dims depends on the size of the planet relative to the star. A Jupiter-sized planet crossing a Sun-like star blocks roughly one per cent of its light; an Earth-sized planet blocks about one hundredth of that. Detecting such small changes requires instruments of extraordinary stability, which is one reason space telescopes, free from the distortions of Earth's atmosphere, have been so productive. The time between successive transits gives the orbital period, from which, using the laws of orbital motion, the planet's distance from its star can be estimated.",
      "The transit method, however, tells astronomers about a planet's size, not its mass. For that, they turn to a different technique. As a planet orbits, it pulls its star slightly towards and away from us, shifting the star's light very slightly towards the blue and then the red end of the spectrum. Measuring this wobble yields an estimate of the planet's mass. When both size and mass are known, the planet's average density can be calculated — and density is a crucial clue to whether a planet is rocky, like Earth, or largely gaseous.",
      "The method has well-known biases. A transit is only visible if the planet's orbit is aligned almost edge-on from our point of view, and the probability of such an alignment decreases as the planet's distance from its star increases. Large planets on short orbits produce deep, frequent dips and are therefore the easiest to find. As a result, early catalogues contained a striking number of 'hot Jupiters' — giant planets orbiting closer to their stars than Mercury does to the Sun. Whether such planets are genuinely common or merely conspicuous was, for a time, a matter of debate; it is now generally accepted that they are relatively rare and that their early prominence was largely an artefact of detection.",
      "False alarms are another concern. A pair of stars eclipsing each other in the background can mimic the signal of a planet, as can certain kinds of stellar activity. Candidates must therefore be confirmed by independent observations before they are counted as planets. Seen in this light, the steady growth of exoplanet catalogues reflects not only better telescopes but also increasingly careful statistical reasoning about what a dip in starlight can and cannot mean.",
    ],
    questions: [
      mcq("tr1", "rd:main-idea", 66, "What is the passage mainly about?", [
        "How the transit method works, what it reveals, and its limitations",
        "The discovery of the first exoplanet",
        "Why hot Jupiters are common",
        "The superiority of space telescopes"], 0, "P1 introduces the method, P2–3 explain what it measures, P4–5 discuss biases and false alarms."),
      mcq("tr2", "rd:detail", 64, "What determines how much a star dims during a transit?", ["The planet's size relative to the star", "The planet's mass", "The distance from Earth", "The planet's density"], 0, "*The amount by which the star dims depends on the size of the planet relative to the star.*",
        [null, "Mass is measured by the wobble method.", "Not mentioned as a factor.", "Density is calculated, not measured from dimming."], [null, "wrong-focus", "out-of-scope", "reversed"]),
      mcq("tr3", "rd:inference", 70, "Why would an Earth-sized planet be harder to detect than a Jupiter-sized one?", [
        "It produces a much smaller dip in the star's light.",
        "It orbits more slowly.",
        "It has less mass.",
        "It is always farther from its star."], 0, "It blocks about one hundredth of what a Jupiter-sized planet blocks — a tiny signal.",
        [null, "Not stated as the reason.", "Mass is irrelevant to the transit signal.", "Overgeneralisation."], [null, "out-of-scope", "wrong-focus", "too-extreme"]),
      mcq("tr4", "rd:purpose", 68, "Why does the author mention density in paragraph 3?", [
        "To show why combining two methods is scientifically valuable",
        "To prove that most exoplanets are gaseous",
        "To explain how the transit method measures mass",
        "To compare Earth and Jupiter"], 0, "Size (transit) + mass (wobble) → density → composition: the value of combining methods.",
        [null, "Not claimed.", "Reverses the logic: transit gives size, not mass.", "Only an illustration."], [null, "over-inference", "reversed", "wrong-focus"]),
      mcq("tr5", "rd:vocab", 68, "The word **conspicuous** in paragraph 4 is closest in meaning to…", ["easy to notice", "dangerous", "numerous", "unusual"], 0, "Contrast *genuinely common* vs. *merely conspicuous* (easily noticed)."),
      mcq("tr6", "rd:inference", 74, "What does the author suggest about early catalogues of exoplanets?", [
        "They gave a misleading impression of how common certain planets are.",
        "They contained mostly false alarms.",
        "They were based on the wobble method only.",
        "They proved that hot Jupiters are the most common planets."], 0, "The *early prominence* of hot Jupiters was *largely an artefact of detection*.",
        [null, "False alarms are discussed separately.", "Not stated.", "Opposite of the current consensus described."], [null, "word-match", "out-of-scope", "contradicts"]),
      mcq("tr7", "rd:organization", 70, "How does paragraph 5 relate to paragraph 4?", ["It adds a second type of problem with the method", "It contradicts paragraph 4", "It gives an example of paragraph 4's claim", "It returns to the history of discovery"], 0, "*False alarms are another concern* — a further limitation after biases."),
      mcq("tr8", "rd:paraphrase", 74, "Which best paraphrases the last sentence?", [
        "Catalogues grow because of both technological progress and more rigorous interpretation of data.",
        "Telescopes are now less important than statistics.",
        "Most dips in starlight are meaningless.",
        "Astronomers have stopped confirming candidates."], 0, "*Not only better telescopes but also increasingly careful statistical reasoning.*",
        [null, "Not compared in importance.", "Too extreme.", "Contradicts the need for confirmation."], [null, "over-inference", "too-extreme", "contradicts"]),
    ],
    annotations: [
      { p: 0, q: "Much of this transformation is due to a deceptively simple idea", type: "claim", note: "Thesis: one method explains much of the change." },
      { p: 3, q: "The method has well-known biases.", type: "limit", note: "Limitation signposted at the start of the paragraph." },
      { p: 3, q: "it is now generally accepted that they are relatively rare", type: "evidence", note: "Current consensus, carefully hedged (*generally*, *relatively*)." },
      { p: 3, q: "largely an artefact of detection", type: "stance", note: "Interpretation: a pattern caused by the method, not by reality." },
      { p: 4, q: "Candidates must therefore be confirmed by independent observations", type: "claim", note: "Methodological principle following from the problem." },
    ],
  },
  {
    id: "r-testing", title: "The Paradox of Effortful Learning", discipline: "psychology", genre: "academic", lvl: 64,
    paragraphs: [
      "Ask students how they prepare for an exam, and many will describe some version of rereading: going over notes, highlighting textbooks, reviewing slides. These strategies feel productive. As the material becomes more familiar, it is processed more fluently, and that fluency is easily mistaken for learning. A substantial body of research in cognitive psychology, however, suggests that this feeling is often misleading.",
      "One of the most robust findings in the field is the so-called testing effect, also known as retrieval practice. In typical experiments, participants study material and then either restudy it or try to recall it without looking. On a test given shortly afterwards, restudying sometimes produces equal or even better performance. On a test given days or weeks later, however, the group that practised retrieval usually remembers considerably more. The act of pulling information out of memory, it seems, does more than measure learning: it changes what is learned, making the information more accessible in the future.",
      "Retrieval practice is one example of what the psychologist Robert Bjork has called 'desirable difficulties' — conditions that make learning feel slower and harder in the short term but improve long-term retention and transfer. Spacing study sessions over time, rather than concentrating them in a single block, is another. So is interleaving, in which different types of problems are mixed rather than practised one type at a time. In each case, the strategy that produces better long-term results tends to feel less effective while it is being used.",
      "This mismatch between how learning feels and how well it works has practical consequences. Learners who judge their progress by how easy the material feels are likely to prefer the less effective strategies and to overestimate how well they will perform later. Teachers face a parallel temptation: lessons that produce smooth, error-free practice may look successful but leave little lasting trace.",
      "The research does have limits. Much of it has been conducted with relatively simple materials, such as word lists or short prose passages, and in laboratory settings. Evidence from classrooms and from complex skills is growing and is broadly encouraging, but effects vary, and difficulties are 'desirable' only if learners can eventually overcome them. A test that is far beyond a learner's current level is not a desirable difficulty; it is simply a difficulty.",
    ],
    questions: [
      mcq("ts1", "rd:main-idea", 62, "What is the central claim of the passage?", [
        "Strategies that feel effective are often less effective for long-term learning than more effortful ones.",
        "Rereading is useless.",
        "Laboratory research does not apply to classrooms.",
        "Tests should replace teaching."], 0, "The *paradox*: fluency feels like learning but effortful strategies work better in the long term.",
        [null, "Too extreme: rereading *sometimes* helps on immediate tests.", "Contradicts P5 (evidence is *broadly encouraging*).", "Out of scope."], [null, "too-extreme", "contradicts", "out-of-scope"]),
      mcq("ts2", "rd:detail", 60, "According to paragraph 2, when does retrieval practice show its clearest advantage?", ["On delayed tests", "On immediate tests", "With difficult vocabulary", "When students restudy"], 0, "*On a test given days or weeks later… the group that practised retrieval usually remembers considerably more.*"),
      mcq("ts3", "rd:inference", 66, "Why might students prefer rereading?", [
        "Because the fluency it creates feels like successful learning",
        "Because teachers recommend it",
        "Because it is always more effective",
        "Because retrieval practice is forbidden"], 0, "P1 and P4: fluency is *easily mistaken for learning*."),
      mcq("ts4", "rd:vocab", 62, "In paragraph 3, **interleaving** refers to…", ["mixing different types of problems during practice", "studying in long single sessions", "testing oneself after reading", "explaining material to others"], 0, "Defined in the text: *different types of problems are mixed rather than practised one type at a time.*"),
      mcq("ts5", "rd:purpose", 66, "Why does the author mention teachers in paragraph 4?", [
        "To show that the same misleading impression can affect instruction",
        "To blame teachers for poor results",
        "To suggest that teachers should test more often",
        "To contrast teachers with learners"], 0, "*Teachers face a parallel temptation*: smooth practice *looks* successful.",
        [null, "Too strong: no blame is assigned.", "Possible implication, but not the purpose of the mention.", "It's a parallel, not a contrast."], [null, "too-extreme", "over-inference", "reversed"]),
      mcq("ts6", "rd:attitude", 68, "How would the author most likely respond to the claim *'The harder the test, the better the learning'*?", [
        "Disagree: difficulties help only if learners can eventually overcome them.",
        "Agree completely.",
        "Agree, but only for simple materials.",
        "The author expresses no view on this."], 0, "Final sentences: a test far beyond the learner's level *is simply a difficulty*.", [null, "Contradicts P5.", "Distorts P5.", "P5 addresses it directly."], [null, "contradicts", "word-match", null]),
      tf("ts7", "rd:detail", 62, "Restudying never produces better results than retrieval practice.", "F", "*On a test given shortly afterwards, restudying sometimes produces equal or even better performance.*"),
      tf("ts8", "rd:detail", 64, "Most research on desirable difficulties has been conducted with complex professional skills.", "F", "*Much of it has been conducted with relatively simple materials… and in laboratory settings.*"),
    ],
    annotations: [
      { p: 0, q: "A substantial body of research in cognitive psychology, however, suggests that this feeling is often misleading.", type: "claim", note: "Thesis, introduced against the common belief (*however*) and hedged (*suggests*, *often*)." },
      { p: 1, q: "On a test given days or weeks later, however, the group that practised retrieval usually remembers considerably more.", type: "evidence", note: "Key experimental evidence; *usually* = hedge." },
      { p: 1, q: "it seems", type: "hedge", note: "Interpretive hedge inserted mid-sentence." },
      { p: 4, q: "The research does have limits.", type: "limit", note: "Limitation paragraph." },
      { p: 4, q: "difficulties are 'desirable' only if learners can eventually overcome them", type: "stance", note: "Qualifies the main claim to prevent overgeneralisation." },
    ],
  },
  {
    id: "r-sticky", title: "Why Prices Stick", discipline: "economics", genre: "academic", lvl: 68,
    paragraphs: [
      "In the simplest economic models, prices adjust instantly to changes in supply and demand. If demand for umbrellas rises during a rainy week, their price should rise; when the sun returns, it should fall. Real-world prices, however, often behave quite differently. Many remain unchanged for months, even when the conditions that originally determined them have shifted. Economists refer to this phenomenon as price stickiness, and it has turned out to be surprisingly important.",
      "Several explanations have been offered. The most intuitive concerns so-called menu costs: changing a price is not free. A restaurant must reprint its menus; a shop must relabel its goods; a firm must update catalogues and inform customers. If these costs are larger than the expected gain from adjusting, it may be rational to leave the price where it is. Critics have objected that such costs are often trivial, especially in an age of digital pricing, and therefore cannot account for much stickiness on their own.",
      "A second family of explanations emphasises contracts and coordination. Wages and many business-to-business prices are fixed in agreements that run for a set period, and firms may hesitate to raise prices if they expect competitors to keep theirs unchanged. A third explanation concerns perceptions of fairness. Surveys conducted by behavioural economists in the 1980s found that many people regard price increases as unfair when they are imposed simply because demand has risen — a hardware store raising the price of snow shovels after a storm, for instance — but acceptable when they reflect higher costs. Firms that value long-term customer relationships may therefore avoid adjustments that, although profitable in the short run, risk being perceived as exploitative.",
      "These explanations are not mutually exclusive, and their relative weight probably differs across industries. What they share is an implication with considerable practical significance. If prices adjusted instantly, changes in the amount of money circulating in an economy would quickly be absorbed by proportional changes in prices, with little effect on output or employment. Because many prices are sticky, monetary policy can, at least in the short run, influence real economic activity. In this sense, a seemingly minor feature of everyday commerce lies close to the heart of central banking.",
    ],
    questions: [
      mcq("sp_1", "rd:main-idea", 64, "What is the main point of the passage?", [
        "Prices often adjust slowly for several reasons, and this has important consequences for policy.",
        "Menu costs are the only reason prices are sticky.",
        "Prices always adjust instantly in real markets.",
        "Behavioural economics has disproved traditional economics."], 0, "The text explains the phenomenon, offers explanations, and draws out the policy implication.",
        [null, "The text presents three families of explanations and critiques menu costs.", "Contradicts P1.", "Out of scope and too extreme."], [null, "partial", "contradicts", "too-extreme"]),
      mcq("sp_2", "rd:detail", 62, "What objection to the menu-cost explanation is mentioned?", ["The costs are often too small to explain much stickiness.", "Menus are rarely reprinted.", "Firms don't care about costs.", "Digital pricing makes prices stickier."], 0, "*Such costs are often trivial… and therefore cannot account for much stickiness on their own.*"),
      mcq("sp_3", "rd:purpose", 66, "Why does the author mention snow shovels?", ["To illustrate a price increase many people consider unfair", "To show that hardware stores have menu costs", "To argue that storms raise costs", "To give an example of a contract"], 0, "It exemplifies an increase *imposed simply because demand has risen*."),
      mcq("sp_4", "rd:inference", 70, "What can be inferred about firms that value long-term customer relationships?", [
        "They may sometimes forgo short-term profit to avoid seeming unfair.",
        "They never raise prices.",
        "They always lose money.",
        "They are mostly hardware stores."], 0, "*May therefore avoid adjustments that, although profitable in the short run, risk being perceived as exploitative.*",
        [null, "Too extreme.", "Not supported.", "Word match with the example."], [null, "too-extreme", "over-inference", "word-match"]),
      mcq("sp_5", "rd:vocab", 66, "**Mutually exclusive** (paragraph 4) means…", ["unable to be true at the same time", "equally important", "supported by evidence", "related to each other"], 0, "If explanations are *not mutually exclusive*, several can be true simultaneously."),
      mcq("sp_6", "rd:inference", 72, "According to the passage, what would happen if all prices adjusted instantly?", [
        "Monetary policy would have little effect on output and employment.",
        "Central banks would control employment more easily.",
        "Prices would never change.",
        "Menu costs would rise."], 0, "Changes in money would be *absorbed by proportional changes in prices, with little effect on output or employment*.",
        [null, "Reversed.", "Contradicts the premise.", "Out of scope."], [null, "reversed", "contradicts", "out-of-scope"]),
      mcq("sp_7", "rd:attitude", 70, "The author's final sentence suggests that price stickiness is…", ["more significant than it might at first appear", "a minor curiosity", "a problem central banks have solved", "mainly a psychological issue"], 0, "*A seemingly minor feature… lies close to the heart of central banking.*"),
    ],
    annotations: [
      { p: 0, q: "it has turned out to be surprisingly important", type: "claim", note: "Thesis, framed as a surprise." },
      { p: 1, q: "Critics have objected that such costs are often trivial", type: "counter", note: "Counterargument to the first explanation." },
      { p: 2, q: "Surveys conducted by behavioural economists in the 1980s found", type: "evidence", note: "Empirical evidence supporting the fairness explanation." },
      { p: 3, q: "their relative weight probably differs across industries", type: "hedge", note: "Hedged synthesis of the explanations." },
      { p: 3, q: "at least in the short run", type: "limit", note: "Scope limitation on the policy claim." },
    ],
  },
  {
    id: "r-aquifer", title: "The Hidden Reservoir", discipline: "geology", genre: "expository", lvl: 72,
    paragraphs: [
      "Most of the world's liquid fresh water is not in rivers or lakes but underground, held in the pores and fractures of rock and sediment. Layers that can store and transmit significant quantities of this groundwater are called aquifers. For many cities and much of the world's irrigated agriculture, aquifers are the principal source of water, and in dry regions they are often the only reliable one.",
      "The crucial question about any aquifer is not simply how much water it contains but how quickly that water is replenished. Water enters aquifers through recharge — mainly rain and snowmelt seeping down through the soil, or leakage from rivers and lakes. In humid regions, recharge may be relatively rapid. In arid regions, however, it can be extremely slow, and some deep aquifers contain water that infiltrated thousands of years ago, under wetter climatic conditions. Such 'fossil' groundwater is, for practical purposes, a non-renewable resource: once pumped out, it will not be replaced on any timescale relevant to human planning.",
      "When extraction exceeds recharge over long periods, water tables fall. Wells must be deepened, pumping becomes more expensive, and springs and streams that depended on groundwater may dry up. A less obvious consequence is land subsidence. As water is removed from fine-grained sediments such as clay, the sediment compacts, and the ground surface above it sinks. Much of this compaction is irreversible: even if water levels later recover, the clay does not fully expand again, and the storage capacity lost is gone for good. Parts of Mexico City, built on the clay beds of a former lake system, have sunk by several metres over the past century, damaging buildings, pipes and drainage systems.",
      "Because groundwater is invisible, its depletion often goes unnoticed until problems are severe. Monitoring is patchy in many regions, and legal frameworks frequently treat groundwater as belonging to whoever owns the land above it, which encourages each user to pump as much as possible before others do. Proposed responses range from metering and pricing to 'managed aquifer recharge', in which surplus surface water — from heavy rains or treated wastewater — is deliberately directed into the ground for storage. None of these measures is a panacea, and each raises technical and political difficulties. What seems clear is that sustainable use requires treating aquifers not as bottomless wells but as shared, finite and slowly changing systems.",
    ],
    questions: [
      mcq("aq1", "rd:main-idea", 68, "What is the passage mainly concerned with?", [
        "The importance of aquifers and the risks of extracting groundwater faster than it is replaced",
        "The geology of Mexico City",
        "How to build deeper wells",
        "The history of fossil water"], 0, "Introduction of aquifers → recharge → consequences of over-extraction → responses."),
      mcq("aq2", "rd:detail", 66, "Why is 'fossil' groundwater described as non-renewable?", [
        "It was recharged under past climatic conditions and is not replaced on human timescales.",
        "It contains fossils.",
        "It is too deep to pump.",
        "It is polluted."], 0, "Recharge happened *thousands of years ago, under wetter climatic conditions*; it won't be replaced *on any timescale relevant to human planning*.",
        [null, "Literal misreading of the metaphor.", "Depth is not the reason given.", "Not mentioned."], [null, "word-match", "out-of-scope", "out-of-scope"]),
      mcq("aq3", "rd:inference", 72, "What can be inferred about land subsidence caused by pumping?", [
        "Restoring water levels will not fully reverse it.",
        "It only occurs in Mexico City.",
        "It affects all types of rock equally.",
        "It increases the aquifer's storage capacity."], 0, "*Much of this compaction is irreversible… the storage capacity lost is gone for good.*",
        [null, "Mexico City is an example.", "The text specifies *fine-grained sediments such as clay*.", "Opposite."], [null, "too-specific", "contradicts", "reversed"]),
      mcq("aq4", "rd:vocab", 70, "**Panacea** (paragraph 4) is closest in meaning to…", ["a solution to every problem", "a dangerous method", "an expensive measure", "a temporary fix"], 0, "*None of these measures is a panacea* = none solves everything."),
      mcq("aq5", "rd:purpose", 72, "Why does the author mention legal frameworks in paragraph 4?", [
        "To explain an institutional factor that encourages over-pumping",
        "To argue that groundwater should be privatised",
        "To describe how monitoring works",
        "To show that the law protects aquifers effectively"], 0, "Ownership tied to land *encourages each user to pump as much as possible before others do* (a tragedy-of-the-commons dynamic).",
        [null, "Reverses the argument.", "Monitoring is a separate point.", "Opposite."], [null, "reversed", "wrong-focus", "contradicts"]),
      mcq("aq6", "rd:attitude", 74, "Which best describes the author's view of proposed responses?", ["Cautious: useful but each with difficulties", "Dismissive", "Enthusiastic: they will solve the problem", "No view is expressed"], 0, "*None… is a panacea, and each raises technical and political difficulties.*"),
      tf("aq7", "rd:detail", 70, "Recharge is generally faster in arid regions than in humid ones.", "F", "Recharge *may be relatively rapid* in humid regions and *extremely slow* in arid ones."),
      tf("aq8", "rd:detail", 72, "Managed aquifer recharge can use treated wastewater.", "T", "*Surplus surface water — from heavy rains or treated wastewater — is deliberately directed into the ground.*"),
      tf("aq9", "rd:detail", 72, "Most countries now have comprehensive groundwater monitoring.", "F", "*Monitoring is patchy in many regions.* (Note: the claim contradicts the text, so it is False rather than Not Given.)"),
    ],
    annotations: [
      { p: 1, q: "The crucial question about any aquifer is not simply how much water it contains but how quickly that water is replenished.", type: "claim", note: "Reframing claim (not X but Y)." },
      { p: 2, q: "Much of this compaction is irreversible", type: "claim", note: "Key causal consequence." },
      { p: 2, q: "Parts of Mexico City, built on the clay beds of a former lake system, have sunk by several metres over the past century", type: "evidence", note: "Concrete example supporting the subsidence claim." },
      { p: 3, q: "None of these measures is a panacea", type: "limit", note: "Limitation of the solutions." },
      { p: 3, q: "What seems clear is that sustainable use requires", type: "stance", note: "Pseudo-cleft + hedge (*seems*) for the writer's conclusion." },
    ],
  },
];
