import type { SpeakingTask } from "./types";

const STD = ["Answered the actual question", "Clear structure (intro, development, wrap-up)", "Supported points with reasons/examples", "Used linking expressions naturally", "Spoke without long unfilled pauses", "Used some precise or academic vocabulary"];

export const SPEAKING_TASKS: SpeakingTask[] = [
  // ------------------------------------------------------------ académico / doctorado
  { id: "phd-rq60", type: "phd", title: "Your research question in 60 seconds", prompt: "Explain your research question in 60 seconds to a professor from another department.", prepSec: 30, speakSec: 60, lvl: 60, checklist: ["Stated the question in one clear sentence", "Explained why it matters", "Gave one concrete example", "Avoided or explained jargon", ...STD.slice(4)], phrases: ["My research looks at…", "The central question is…", "This matters because…", "For example, …", "What I hope to show is…"] },
  { id: "sp-summarise-article", type: "academic", title: "Summarise an article", prompt: "Summarise the argument of a reading you completed in the app (or an article you know well) as if to a seminar group.", prepSec: 45, speakSec: 90, lvl: 62, checklist: ["Named the source and main claim", "Explained the key evidence", "Mentioned a limitation", "Kept own opinion separate", ...STD.slice(3)], phrases: ["The author argues that…", "Her main evidence comes from…", "One limitation is…", "What I found interesting was…"] },
  { id: "sp-method-prof", type: "phd", title: "Explain your methodology to a professor", prompt: "A professor asks: *“Why did you choose that method rather than, say, a large survey?”* Explain and justify your methodology.", prepSec: 30, speakSec: 75, lvl: 64, checklist: ["Described the method precisely", "Justified it against the alternative", "Acknowledged a trade-off", ...STD.slice(4)], phrases: ["I opted for… because…", "A survey would have given us…, but…", "The trade-off is that…", "To compensate for that, …"] },
  { id: "sp-defend", type: "phd", title: "Defend your interpretation", prompt: "Someone says your interpretation of your data is speculative. Defend it politely but firmly.", prepSec: 30, speakSec: 60, lvl: 66, checklist: ["Acknowledged the objection", "Gave specific evidence", "Conceded what is fair", "Maintained position", "Polite tone"], phrases: ["I take your point, but…", "The evidence for this comes from…", "I'd agree that it's not conclusive; however…", "That's why I've framed it as…"] },
  { id: "sp-agree-author", type: "academic", title: "Do you agree with the author?", prompt: "Do you agree with the author's conclusion in *The Paradox of Effortful Learning*? Explain why, with an example from your own experience as a learner or teacher.", prepSec: 30, speakSec: 75, lvl: 62, checklist: ["Clear position", "Engaged with the author's argument", "Personal example linked to the argument", ...STD.slice(4)] },
  { id: "sp-challenge", type: "phd", title: "A professor challenges you", prompt: "In your viva, an examiner says: *“Your sample is far too small to say anything about the community as a whole.”* Respond.", prepSec: 20, speakSec: 60, lvl: 68, checklist: ["Did not become defensive", "Clarified the scope of the claim", "Explained why the data are still informative", "Mentioned future work"], phrases: ["That's a fair concern.", "I'm not claiming that…; what I'm claiming is…", "Within that scope, …", "A larger sample would allow…"] },
  { id: "sp-lay", type: "academic", title: "Explain a complex concept to a non-specialist", prompt: "Explain what a *phoneme* is (or another key concept from your field) to someone with no background in linguistics.", prepSec: 30, speakSec: 60, lvl: 60, checklist: ["Used an everyday analogy or example", "Avoided unexplained jargon", "Checked the main point was clear", ...STD.slice(4)] },
  { id: "sp-question", type: "phd", title: "Ask a question after a talk", prompt: "You've just heard a conference talk on tone loss in an Otomanguean language. Ask the speaker a clear, polite, substantive question (thank them, give brief context, ask one question).", prepSec: 20, speakSec: 30, lvl: 62, checklist: ["Thanked the speaker briefly", "Gave one sentence of context", "Asked ONE clear question", "Didn't give a mini-lecture"], phrases: ["Thank you for a fascinating talk.", "You mentioned that…", "I was wondering whether…", "Could you say a bit more about…?"] },
  { id: "sp-disagree-colleague", type: "phd", title: "Disagree with a fellow researcher", prompt: "A colleague claims that documenting a language is pointless if it's going to disappear anyway. Disagree respectfully.", prepSec: 20, speakSec: 60, lvl: 64, checklist: ["Acknowledged their view", "Gave at least two reasons", "Used softening devices", "Kept a collegial tone"] },
  { id: "sp-uncertainty", type: "phd", title: "Admit uncertainty", prompt: "Your supervisor asks a question you can't answer yet: *“How does tone interact with stress in compounds?”* Respond honestly, showing what you do know and how you'll find out.", prepSec: 15, speakSec: 45, lvl: 62, checklist: ["Admitted uncertainty without apologising excessively", "Shared what you do know", "Proposed a concrete next step"], phrases: ["To be honest, I haven't looked at that systematically yet.", "What I can say is…", "My plan is to…", "I'll get back to you on that."] },
  { id: "sp-present-results", type: "phd", title: "Present a result", prompt: "Present one (real or hypothetical) result from your research as if showing a slide: what the figure shows, the main pattern, and what it might mean.", prepSec: 30, speakSec: 75, lvl: 64, checklist: ["Oriented the audience to the figure", "Highlighted ONE main pattern", "Gave numbers or comparisons", "Hedged the interpretation"], phrases: ["What you can see here is…", "The key thing to notice is…", "This suggests…", "Although we need more data, …"] },

  // ------------------------------------------------------------ general / exam-like
  { id: "sp-general-1", type: "general", title: "A place that matters", prompt: "Describe a place that has been important in your intellectual development and explain why.", prepSec: 30, speakSec: 60, lvl: 56, checklist: STD },
  { id: "sp-ielts-p2", type: "exam", exam: "ielts", title: "IELTS Part 2 — Long turn", prompt: "Describe a skill you learned that took a long time to master.\n\nYou should say:\n- what the skill is\n- how you learned it\n- what difficulties you had\n\nand explain how you felt when you finally mastered it.", prepSec: 60, speakSec: 120, lvl: 58, checklist: ["Covered all points on the card", "Spoke for close to 2 minutes", "Narrative was organised", "Range of tenses", ...STD.slice(4)] },
  { id: "sp-ielts-p3", type: "exam", exam: "ielts", title: "IELTS Part 3 — Discussion", prompt: "Why do you think some people give up learning a new skill while others persist? Do you think schools prepare students well for long-term learning?", prepSec: 5, speakSec: 90, lvl: 62, checklist: ["Gave extended answers, not one sentence", "Speculated and generalised appropriately", "Compared perspectives", ...STD.slice(4)] },
  { id: "sp-cae-p2", type: "exam", exam: "cae", title: "C1 Advanced Part 2 — Long turn (adapted)", context: "In the real exam you compare two of three photographs. Here, imagine these two scenes: (A) a student recording an elderly speaker's stories in a village kitchen; (B) a large lecture hall where a professor is teaching a linguistics class.", prompt: "Compare the two situations and say **what the people might be learning** and **how challenging the situation might be for them**.", prepSec: 10, speakSec: 60, lvl: 62, checklist: ["Compared rather than described separately", "Answered both questions", "Speculated (might, could, it looks as if)", "Kept to about 1 minute"] },
  { id: "sp-cpe-p3", type: "exam", exam: "cpe", title: "C2 Proficiency Part 3 — Long turn", prompt: "**How important is it for a society to preserve its languages?**\n\nYou may consider:\n- identity and culture\n- economic opportunities\n- the role of education", prepSec: 10, speakSec: 120, lvl: 72, checklist: ["Developed a coherent argument for 2 minutes", "Went beyond the prompts", "Used sophisticated, precise language", "Maintained fluency", "Concluded clearly"] },
  { id: "sp-toefl-interview", type: "interview", exam: "toefl", title: "TOEFL — Take an Interview (practice)", prompt: "You are taking part in a research interview about study habits. Answer the interviewer's question: *“Some students prefer to study alone, while others prefer study groups. Which do you prefer, and why?”*", prepSec: 0, speakSec: 45, lvl: 58, checklist: ["Direct answer in the first sentence", "One clear reason with an example", "Natural, conversational fluency", "Used the full 45 seconds"] },

  // ------------------------------------------------------------ repetición (pronunciación / TOEFL Listen and Repeat)
  { id: "rep-1", type: "repeat", title: "Listen and repeat 1", prompt: "Listen and repeat the sentence exactly.", target: "The library opens at eight.", prepSec: 0, speakSec: 8, lvl: 45, checklist: ["Every word reproduced"] },
  { id: "rep-2", type: "repeat", title: "Listen and repeat 2", prompt: "Listen and repeat the sentence exactly.", target: "Please return your books to the desk on the left.", prepSec: 0, speakSec: 8, lvl: 50, checklist: ["Every word reproduced"] },
  { id: "rep-3", type: "repeat", title: "Listen and repeat 3", prompt: "Listen and repeat the sentence exactly.", target: "Students who need extra time should speak to their advisor first.", prepSec: 0, speakSec: 10, lvl: 55, checklist: ["Every word reproduced"] },
  { id: "rep-4", type: "repeat", title: "Listen and repeat 4", prompt: "Listen and repeat the sentence exactly.", target: "The seminar has been moved to the room next to the language laboratory.", prepSec: 0, speakSec: 10, lvl: 60, checklist: ["Every word reproduced"] },
  { id: "rep-5", type: "repeat", title: "Listen and repeat 5", prompt: "Listen and repeat the sentence exactly.", target: "If the recordings aren't uploaded by Friday, the transcriptions will have to wait until next month.", prepSec: 0, speakSec: 12, lvl: 66, checklist: ["Every word reproduced"] },
  { id: "rep-6", type: "repeat", title: "Listen and repeat 6", prompt: "Listen and repeat the sentence exactly.", target: "Although the results were statistically significant, the effect was considerably smaller than the committee had anticipated.", prepSec: 0, speakSec: 12, lvl: 72, checklist: ["Every word reproduced"] },
];
