import type { WritingTask } from "./types";

const ACAD_CHECK = ["Clear main point / thesis", "Logical paragraphing with topic sentences", "Claims supported by reasons or evidence", "Appropriate hedging (not over- or under-claiming)", "Formal academic register", "Varied, precise vocabulary", "Accurate grammar and punctuation"];

export const WRITING_TASKS: WritingTask[] = [
  // ------------------------------------------------------------ producción corta
  { id: "w-use-words", genre: "Short response", title: "Use it or lose it", prompt: "Write about 60 words on any academic topic you like, using **at least two** of the vocabulary items you have recently learned (shown above). Use them precisely — not just to tick a box.", lvl: 55, minWords: 55, maxWords: 90, focus: ["vocabulary", "precision"], checklist: ["Uses at least two target words", "Each word is used with its correct meaning and collocations", "The paragraph makes sense as a whole"], mustUseVocab: 2 },
  { id: "w-paragraph-claim", genre: "Paragraph", title: "One claim, one paragraph", prompt: "Write one academic paragraph (100–140 words) defending this claim: *Fieldwork recordings should be archived in formats the community itself can access.* Include a topic sentence, two supporting reasons with an example, and a concluding sentence.", lvl: 58, minWords: 100, maxWords: 150, focus: ["paragraph structure", "topic sentences", "argumentation"], checklist: ["Topic sentence states the claim", "Two distinct reasons", "At least one concrete example", "Concluding sentence that doesn't just repeat", ...ACAD_CHECK.slice(3)], phrases: ["A strong case can be made for…", "First, …", "A further reason is that…", "For instance, …", "It follows that…"] },
  { id: "w-compare", genre: "Comparison", title: "Compare two methods", prompt: "In 120–160 words, compare **elicitation with word lists** and **recording spontaneous conversation** as methods for studying a language's sound system. Identify one advantage and one disadvantage of each and conclude which you would prioritise for a first description, and why.", lvl: 62, minWords: 120, maxWords: 170, focus: ["comparison", "cohesion", "evaluation"], checklist: ["Both methods described fairly", "Clear comparative structures (whereas, while, in contrast)", "A justified conclusion", ...ACAD_CHECK.slice(4)], phrases: ["Whereas X allows…, Y…", "In contrast, …", "Both methods…", "The main drawback of X is that…", "On balance, …"] },
  { id: "w-opinion", genre: "Academic opinion", title: "Take a position", prompt: "Write 150–200 words: *Should universities require PhD theses to be written in English?* State your position, give two reasons, acknowledge one counterargument and respond to it.", lvl: 62, minWords: 150, maxWords: 210, focus: ["argumentation", "stance", "counterargument"], checklist: ["Clear position early", "Two reasons", "Counterargument presented fairly", "Rebuttal", ...ACAD_CHECK.slice(3)] },

  // ------------------------------------------------------------ fuentes
  { id: "w-paraphrase", genre: "Paraphrase", title: "Paraphrase without patchwriting", prompt: "Paraphrase the following sentence in one or two sentences, changing the structure, keeping the meaning and the level of certainty, and adding a citation:\n\n> *Although bilingual education programmes are frequently credited with reversing language shift, the evidence suggests that their effect depends heavily on whether the language is also used outside school.* (Aguilar, 2017)", lvl: 62, minWords: 25, maxWords: 70, focus: ["paraphrase", "hedging"], checklist: ["Different sentence structure", "Same meaning and nuance (frequently credited / depends heavily)", "Citation included", "No long strings copied from the original"] },
  { id: "w-summary", genre: "Summary", title: "Summarise a reading", prompt: "Choose one of the reading texts in the app (e.g., *What Ancient Teeth Remember*) and summarise it in **90–120 words** for a classmate who hasn't read it. Include its main claim, how it supports it, and its main limitation.", lvl: 60, minWords: 90, maxWords: 130, focus: ["summarizing", "concision"], checklist: ["Main claim in the first sentence", "Key support, no minor details", "Limitation included", "In my own words", "Within word limit"] },
  { id: "w-synthesis", genre: "Synthesis", title: "Synthesise three sources", prompt: "Write a 150–200 word synthesis paragraph that combines these three findings (organise by idea, not by source):", sources: ["Source A (2016): Children in bilingual schools in Oaxaca used the Indigenous language more at home than children in Spanish-only schools.", "Source B (2019): In Chihuahua, bilingual schooling had no measurable effect on home language use when the teacher did not speak the local variety.", "Source C (2022): Teachers' proficiency in the local variety was the strongest predictor of students' attitudes towards the language."], lvl: 68, minWords: 150, maxWords: 210, focus: ["synthesis", "reporting verbs", "hedging"], checklist: ["Organised around an idea", "Shows how sources relate (agree, conflict, explain)", "Reporting verbs reflect certainty", "Ends with an implication or gap", "Citations are accurate"] },
  { id: "w-critique", genre: "Critique", title: "Critique an argument", prompt: "Read the claim and write a 150–200 word critique:\n\n> *Since speakers in our survey who used social media in their heritage language reported more positive attitudes towards it, governments should fund social media campaigns to save endangered languages.*\n\nIdentify at least two weaknesses in the reasoning and suggest what evidence would be needed.", lvl: 68, minWords: 150, maxWords: 210, focus: ["critical thinking", "argumentation", "academic politeness"], checklist: ["Identifies correlation vs. causation", "Identifies a second weakness (sample, self-report, leap to policy…)", "Suggests appropriate evidence", "Tone is critical but respectful"] },
  { id: "w-response", genre: "Response to a text", title: "Respond to an author", prompt: "Write a 180–230 word response to the passage *The Visible Translator*: summarise Venuti's position in two sentences, then argue whether foreignising translation is appropriate for literature from minority Indigenous languages.", lvl: 70, minWords: 180, maxWords: 240, focus: ["summary + evaluation", "stance"], checklist: ["Accurate summary", "Clear position", "Engages with the objections in the text", ...ACAD_CHECK.slice(3)] },

  // ------------------------------------------------------------ escritura de investigación
  { id: "w-abstract", genre: "Abstract", title: "Write an abstract", prompt: "Write a 150–200 word abstract for your thesis (or a planned study). Use the moves: **context → gap → aim → method → (expected) results → contribution**.", lvl: 66, minWords: 150, maxWords: 220, focus: ["genre moves", "concision", "tense"], checklist: ["Context in 1–2 sentences", "Explicit gap", "Aim stated clearly", "Method summarised", "Results or expected results", "Contribution / implication", "No citations or unexplained abbreviations"], phrases: ["Despite…, little is known about…", "This study examines…", "Drawing on…", "The results indicate that…", "These findings contribute to…"] },
  { id: "w-conf-abstract", genre: "Conference abstract", title: "Conference abstract (300 words)", prompt: "Write a conference abstract (250–300 words) for a phonology conference presenting preliminary results from your research. Include a title.", lvl: 70, minWords: 250, maxWords: 320, focus: ["genre", "persuasion", "hedging of preliminary results"], checklist: ["Informative title", "Clear research question", "Data and method", "Preliminary results appropriately hedged", "Why it matters to the audience"] },
  { id: "w-litreview", genre: "Literature review", title: "Literature review paragraph", prompt: "Write a literature review paragraph (200–250 words) on research about one topic related to your thesis (e.g., tone in Uto-Aztecan languages, documentation of endangered languages, phonological description methods). Use at least three sources you know; organise them thematically and end with a gap.", lvl: 70, minWords: 200, maxWords: 270, focus: ["synthesis", "reporting verbs", "gap statement"], checklist: ["Thematic organisation", "At least three sources related to each other", "Reporting verbs chosen carefully", "Ends with a specific gap", "No invented citations"] },
  { id: "w-method", genre: "Methodology", title: "Methodology section", prompt: "Write a methodology section (200–260 words) for your research: participants/consultants, materials, procedure, analysis, ethics. Justify at least two decisions.", lvl: 66, minWords: 200, maxWords: 280, focus: ["precision", "tense and voice", "justification"], checklist: ["Participants described precisely", "Materials and procedure replicable", "Analysis described", "Ethics mentioned", "Two decisions justified", "Past tense, consistent voice"] },
  { id: "w-discussion", genre: "Discussion", title: "Discussion section", prompt: "Imagine your study found that younger speakers produce a contrast less consistently than older speakers. Write a discussion section (220–280 words): interpret the result, relate it to (real or hypothetical) previous research, offer two possible explanations, note one limitation and one implication.", lvl: 72, minWords: 220, maxWords: 300, focus: ["interpretation", "hedging", "limitations"], checklist: ["Restates the main finding briefly", "Interpretation is hedged", "Two alternative explanations", "Limitation with its effect", "Implication or future research"] },
  { id: "w-proposal", genre: "Research proposal", title: "Research proposal summary", prompt: "Write a 250–300 word research proposal summary for a doctoral application: background, research questions, methodology, significance and feasibility.", lvl: 72, minWords: 250, maxWords: 320, focus: ["persuasion", "structure", "precision"], checklist: ["Background establishes importance", "Specific research questions", "Feasible methodology", "Significance stated", "Confident but hedged tone"] },
  { id: "w-explain-lay", genre: "Explanation of research", title: "Explain your research to a non-specialist", prompt: "Explain your thesis research to an educated non-linguist (e.g., a scholarship committee member from another field) in 150–200 words. Avoid jargon or explain it.", lvl: 64, minWords: 150, maxWords: 210, focus: ["clarity", "audience awareness"], checklist: ["No unexplained jargon", "Concrete example", "Why it matters", "Engaging but accurate"] },
  { id: "w-email-supervisor", genre: "Academic email", title: "Email to a potential supervisor", prompt: "Write an email (150–200 words) to a professor abroad asking whether they might supervise your PhD. Mention your background, project and a specific, polite request.", lvl: 60, minWords: 150, maxWords: 210, focus: ["register", "politeness", "concision"], checklist: ["Specific subject line", "Purpose in first two sentences", "Relevant background only", "Specific request", "Appropriate closing"] },
  { id: "w-email-extension", genre: "Academic email", title: "Asking for an extension", prompt: "Write a short email (90–130 words) to a journal editor asking for a two-week extension to submit revisions, explaining the reason briefly and proposing a new date.", lvl: 58, minWords: 90, maxWords: 140, focus: ["politeness", "concision"], checklist: ["Polite, direct request", "Brief reason", "Concrete new date", "Thanks and closing"] },

  // ------------------------------------------------------------ exámenes
  { id: "w-toefl-email", genre: "TOEFL: Write an Email", exam: "toefl", title: "TOEFL — Write an Email", prompt: "**Scenario.** You are a member of a university language club. The club's coordinator, Professor Daniels, has asked members to suggest an activity for International Mother Language Day.\n\nWrite an email to Professor Daniels in which you:\n- propose an activity,\n- explain why it would interest students,\n- offer to help with one specific task.", lvl: 56, minWords: 100, timeMin: 7, focus: ["task completion", "social conventions", "organisation"], checklist: ["All three points addressed", "Appropriate greeting and closing", "Polite, semi-formal tone", "Clear, organised paragraphs"] },
  { id: "w-toefl-disc", genre: "TOEFL: Academic Discussion", exam: "toefl", title: "TOEFL — Write for an Academic Discussion", prompt: "**Professor Lin (Sociology):** Next week we'll discuss technology and communities. Some argue that online translation tools will make learning foreign languages unnecessary. Do you agree? Why or why not?\n\n**Maya:** I think they will. The tools are getting better every year, and most people only need basic communication for travel or work.\n\n**Daniel:** I disagree. Translation tools miss culture and nuance, and relationships depend on more than exchanging information.\n\nWrite a response that contributes to the discussion (at least 100 words).", lvl: 58, minWords: 100, timeMin: 10, focus: ["contributing a new idea", "supporting an opinion", "language use"], checklist: ["States own position clearly", "Adds a NEW reason (not just repeating Maya/Daniel)", "Supports with explanation or example", "Refers to classmates' ideas", "100+ words, varied language"] },
  { id: "w-ielts-t1", genre: "IELTS Task 1", exam: "ielts", title: "IELTS Academic — Task 1", prompt: "The table shows the percentage of speakers of an Indigenous language, by age group, who reported using it daily in 1990, 2005 and 2020.\n\n| Age group | 1990 | 2005 | 2020 |\n|---|---|---|---|\n| 60+ | 92% | 90% | 88% |\n| 35–59 | 85% | 74% | 61% |\n| 18–34 | 71% | 48% | 29% |\n| Under 18 | 58% | 31% | 12% |\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.", lvl: 60, minWords: 150, timeMin: 20, focus: ["overview", "key features", "comparisons", "data accuracy"], checklist: ["Paraphrased introduction", "Clear OVERVIEW of main trends", "Key figures selected (not all numbers)", "Accurate comparisons", "No opinions or causes invented", "150+ words"], phrases: ["Overall, …", "The most striking change was…", "…fell sharply from X to Y", "…remained relatively stable at around…", "In contrast, …", "By 2020, …"] },
  { id: "w-ielts-t2", genre: "IELTS Task 2", exam: "ielts", title: "IELTS Academic — Task 2", prompt: "Some people believe that governments should spend money on preserving endangered languages, while others think this money would be better spent on teaching widely spoken languages.\n\nDiscuss both views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.", lvl: 62, minWords: 250, timeMin: 40, focus: ["task response", "coherence and cohesion", "lexical resource", "grammatical range and accuracy"], checklist: ["Both views discussed", "Own opinion clear throughout", "Well-developed paragraphs with examples", "Range of cohesive devices (not mechanical)", "Wide, precise vocabulary", "Range of complex structures, mostly error-free"] },
  { id: "w-cae-essay", genre: "C1 Advanced: Essay", exam: "cae", title: "C1 Advanced — Part 1 Essay", prompt: "Your class has watched a panel discussion about ways in which universities could support students from Indigenous communities. You have made the notes below.\n\n**Ways universities could support Indigenous students:**\n- scholarships\n- courses taught in Indigenous languages\n- mentoring programmes\n\n**Some opinions expressed in the discussion:**\n- \"Money is the biggest barrier.\"\n- \"Students need to see their language valued.\"\n- \"Mentors who share your background make a real difference.\"\n\nWrite an **essay** discussing **two** of the ways in your notes. You should **explain which way you think is more important**, giving reasons to support your opinion. You may, if you wish, make use of the opinions expressed, but use your own words as far as possible. Write **220–260 words**.", lvl: 64, minWords: 220, maxWords: 260, timeMin: 45, focus: ["content", "communicative achievement", "organisation", "language"], checklist: ["Discusses exactly two methods", "Says which is more important, with reasons", "Opinions paraphrased, not copied", "Clear paragraphing and linking", "Range of vocabulary and structures", "220–260 words"] },
  { id: "w-cae-proposal", genre: "C1 Advanced: Proposal", exam: "cae", title: "C1 Advanced — Part 2 Proposal", prompt: "The director of your university's language centre wants to improve the support offered to international postgraduate students. You have been asked to write a **proposal** recommending two improvements, explaining how they would benefit students and how they could be implemented.\n\nWrite your proposal in **220–260 words**.", lvl: 64, minWords: 220, maxWords: 260, timeMin: 45, focus: ["genre conventions (headings, recommendations)", "persuasion", "register"], checklist: ["Title and clear headings", "Introduction stating purpose", "Two recommendations with benefits", "Implementation suggested", "Persuasive conclusion", "Consistently formal-neutral register"] },
  { id: "w-cae-review", genre: "C1 Advanced: Review", exam: "cae", title: "C1 Advanced — Part 2 Review", prompt: "An international student magazine has asked readers to submit **reviews** of a book or documentary that changed the way they think about language. Write a review describing the work, explaining what you learned and saying who would most benefit from it.\n\nWrite **220–260 words**.", lvl: 62, minWords: 220, maxWords: 260, timeMin: 45, focus: ["description + evaluation", "engaging style"], checklist: ["Engaging title/opening", "Brief description (no long plot summary)", "Clear evaluation with reasons", "Recommendation to a specific audience", "Engaging, varied language"] },
  { id: "w-cpe-essay", genre: "C2 Proficiency: Essay", exam: "cpe", title: "C2 Proficiency — Part 1 Essay", prompt: "Read the two texts below. Write an **essay summarising and evaluating the key points from both texts**. Use your own words throughout as far as possible, and include your own ideas in your answer. Write **240–280 words**.", sources: [
    "**Text 1 — Documentation before description?** Linguists working on endangered languages have increasingly prioritised documentation — creating large, well-annotated archives of recordings — over writing grammars. The rationale is compelling: a grammar reflects one analyst's theory, which may be superseded, whereas a rich record of the language in use can be reanalysed by future generations. Critics, however, warn that archives without accompanying analysis risk becoming digital graveyards, consulted by no one.",
    "**Text 2 — Whose record is it?** For many communities, the question is not whether recordings or grammars are more valuable, but who controls them. Archives held in foreign universities, accessible only to researchers, can reproduce older patterns of extraction. When communities set the priorities, documentation often looks quite different: recordings of songs, everyday conversations and teaching materials may matter more to speakers than the elicited paradigms linguists traditionally collect."],
    lvl: 74, minWords: 240, maxWords: 280, timeMin: 50, focus: ["summary of both texts", "evaluation", "own ideas", "paraphrase"], checklist: ["Summarises the key points of BOTH texts", "Evaluates them (not just reports)", "Adds own ideas", "Paraphrases throughout", "Cohesive essay structure", "240–280 words"] },
  { id: "w-cpe-article", genre: "C2 Proficiency: Article", exam: "cpe", title: "C2 Proficiency — Part 2 Article", prompt: "A science magazine is running a series called *The Ideas That Changed My Mind*. Write an **article** about an academic idea that changed how you see the world, explaining what the idea is, why it affected you, and whether you think it deserves wider recognition.\n\nWrite **280–320 words**.", lvl: 74, minWords: 280, maxWords: 320, timeMin: 45, focus: ["engaging style", "explanation for non-specialists", "sophisticated language"], checklist: ["Engaging title and hook", "Idea explained clearly for a general reader", "Personal impact conveyed", "Evaluation of its recognition", "Sophisticated, controlled language", "280–320 words"] },
];
